import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import GymPovider from "./GymContext/Context";
import { ToastContainer } from "react-toastify";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "FITLOG App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col`}>
        <GymPovider>
          <Navbar></Navbar>
          <main className={`${oswald.className}`}>
            {children}
          </main>
          <ToastContainer />
          <Footer></Footer>
        </GymPovider>
      </body>
    </html>
  );
}
